// Mock data for PurePlate
// This file serves as the data source for our mock API service.

export interface Ingredient {
  id: string
  name: string
  origin: string
  farm: string
  description: string
  image: string
  labResult: string
}

export interface Meal {
  id: string
  slug: string
  name: string
  description: string
  price: number
  rating: number
  reviews: number
  image: string
  images: string[]
  calories: number
  protein: number
  carbs: number
  fats: number
  badges: string[]
  tags: string[]
  vendorId: string
  vendorName: string
  ingredients: Ingredient[]
  labReportId: string
  category: string
  restaurantName: string
  isVeg: boolean
  discount?: number
  detailedDescription: string // "what is it made of"
  ingredientsList: string[] // Simple list for detail view
}

export const INGREDIENTS_DB: Record<string, Ingredient> = {
  spinach: {
    id: "ing-1",
    name: "Organic Spinach",
    origin: "Salinas Valley, CA",
    farm: "GreenLeaf Family Farms",
    description: "Harvested this morning, pesticide-free.",
    image: "/placeholder.svg?key=wmbii",
    labResult: "PASS: No heavy metals detected.",
  },
  quinoa: {
    id: "ing-2",
    name: "Red Quinoa",
    origin: "Andes Mountains, Peru",
    farm: "Cooperative BioAndes",
    description: "Ancient grain, fair trade certified.",
    image: "/placeholder.svg?key=4sv39",
    labResult: "PASS: 100% Organic certified.",
  },
  chicken: {
    id: "ing-3",
    name: "Free-Range Chicken",
    origin: "Sonoma, CA",
    farm: "Happy Hen Ranch",
    description: "Antibiotic-free, roam-free poultry.",
    image: "/placeholder.svg?key=adf4t",
    labResult: "PASS: Salmonella negative. Antibiotic negative.",
  },
}

export const MEALS_DB: Meal[] = [
  {
    id: "1",
    slug: "super-green-quinoa-bowl",
    name: "Super Green Quinoa Bowl",
    description: "A nutrient-packed bowl with antioxidant-rich spinach, kale, and protein-packed quinoa.",
    price: 14.99,
    rating: 4.9,
    reviews: 128,
    image: "/super-green-quinoa-bowl.jpg",
    images: ["/public/bowl-of-quinoa.png", "/public/fresh-spinach.png"],
    calories: 450,
    protein: 18,
    carbs: 55,
    fats: 12,
    badges: ["Zero-Adulteration", "Organic", "High-Protein"],
    tags: ["Vegan", "Lunch", "Gluten-Free"],
    vendorId: "v1",
    vendorName: "GreenLeaf Family Farms",
    category: "vegan",
    labReportId: "LAB-8821",
    ingredients: [INGREDIENTS_DB["spinach"], INGREDIENTS_DB["quinoa"]],
    restaurantName: "GreenLeaf Kitchen",
    isVeg: true,
    discount: 10,
    detailedDescription:
      "A vibrant mix of organic supergreens including spinach and kale, tossed with fluffy quinoa and a zesty lemon vinaigrette. Topped with crunchy pumpkin seeds for texture.",
    ingredientsList: ["Organic Spinach", "Red Quinoa", "Kale", "Lemon Vinaigrette", "Pumpkin Seeds"],
  },
  {
    id: "2",
    slug: "grilled-chicken-harvest",
    name: "Grilled Chicken Harvest",
    description: "Lean grilled chicken breast with roasted root vegetables and a lemon-herb dressing.",
    price: 16.5,
    rating: 4.8,
    reviews: 95,
    image: "/grilled-chicken-salad.png",
    images: ["/public/grilled-chicken-salad.png"],
    calories: 520,
    protein: 42,
    carbs: 30,
    fats: 18,
    badges: ["Antibiotic-Free", "Zero-Adulteration"],
    tags: ["High-Protein", "Paleo", "Dinner"],
    vendorId: "v2",
    vendorName: "Happy Hen Ranch",
    category: "high-protein",
    labReportId: "LAB-9932",
    ingredients: [INGREDIENTS_DB["chicken"]],
    restaurantName: "Ranch House Grill",
    isVeg: false,
    detailedDescription:
      "Juicy free-range chicken breast grilled to perfection, served alongside a medley of roasted carrots, parsnips, and sweet potatoes.",
    ingredientsList: ["Free-Range Chicken Breast", "Carrots", "Parsnips", "Sweet Potatoes", "Herb Blend"],
  },
  {
    id: "3",
    slug: "mediterranean-chickpea-stew",
    name: "Mediterranean Chickpea Stew",
    description: "Hearty stew with chickpeas, tomatoes, and mediterranean herbs.",
    price: 12.99,
    rating: 4.7,
    reviews: 64,
    image: "/chickpea-stew.jpg",
    images: ["/public/chickpea-stew.jpg"],
    calories: 380,
    protein: 14,
    carbs: 60,
    fats: 8,
    badges: ["Heart-Healthy"],
    tags: ["Vegan", "Diabetic-Friendly", "Low-Fat"],
    vendorId: "v3",
    vendorName: "Sunny Fields",
    category: "diabetic-friendly",
    labReportId: "LAB-7741",
    ingredients: [],
    restaurantName: "Mediterranean Delights",
    isVeg: true,
    discount: 15,
    detailedDescription:
      "Slow-cooked stew featuring tender chickpeas simmered in a rich tomato broth infused with oregano, basil, and garlic.",
    ingredientsList: ["Chickpeas", "Tomatoes", "Onions", "Garlic", "Mediterranean Herbs"],
  },
  {
    id: "4",
    slug: "wild-salmon-poke",
    name: "Wild Salmon Poke",
    description: "Sustainably caught salmon with edamame, avocado, and brown rice.",
    price: 18.99,
    rating: 5.0,
    reviews: 210,
    image: "/salmon-poke-bowl.png",
    images: ["/public/salmon-poke-bowl.png"],
    calories: 560,
    protein: 35,
    carbs: 45,
    fats: 22,
    badges: ["Omega-3 Rich", "Zero-Adulteration"],
    tags: ["Pescatarian", "Lunch"],
    vendorId: "v4",
    vendorName: "Ocean Fresh",
    category: "seafood",
    labReportId: "LAB-3321",
    ingredients: [],
    restaurantName: "Pacific Catch",
    isVeg: false,
    detailedDescription:
      "Fresh, sushi-grade wild salmon cubes marinated in soy-ginger sauce, served over nutty brown rice with creamy avocado and crisp edamame.",
    ingredientsList: ["Wild Salmon", "Brown Rice", "Avocado", "Edamame", "Soy-Ginger Sauce"],
  },
  {
    id: "5",
    slug: "keto-avocado-burger",
    name: "Keto Avocado Burger",
    description: "Grass-fed beef patty wrapped in lettuce with generous avocado slices.",
    price: 15.5,
    rating: 4.6,
    reviews: 88,
    image: "/keto-burger.jpg",
    images: [],
    calories: 610,
    protein: 30,
    carbs: 8,
    fats: 45,
    badges: ["Keto-Certified"],
    tags: ["Keto", "Low-Carb"],
    vendorId: "v5",
    vendorName: "Rancheros",
    category: "keto",
    labReportId: "LAB-1123",
    ingredients: [],
    restaurantName: "The Burger Joint",
    isVeg: false,
    detailedDescription:
      "A juicy grass-fed beef patty served in a crisp lettuce wrap, topped with fresh avocado slices and a hint of spicy mayo.",
    ingredientsList: ["Grass-Fed Beef", "Iceberg Lettuce", "Avocado", "Spicy Mayo", "Red Onion"],
  },
  {
    id: "6",
    slug: "berry-blast-smoothie",
    name: "Berry Blast Smoothie",
    description: "Antioxidant-rich blend of blueberries, strawberries, and acai.",
    price: 8.5,
    rating: 4.9,
    reviews: 340,
    image: "/berry-smoothie.png",
    images: [],
    calories: 220,
    protein: 5,
    carbs: 40,
    fats: 2,
    badges: ["No-Added-Sugar"],
    tags: ["Smoothie", "Breakfast", "Snack"],
    vendorId: "v1",
    vendorName: "GreenLeaf Family Farms",
    category: "beverages",
    labReportId: "LAB-5543",
    ingredients: [],
    restaurantName: "Juice Press",
    isVeg: true,
    detailedDescription:
      "A refreshing blend of organic blueberries, strawberries, and acai berries, mixed with almond milk for a smooth finish.",
    ingredientsList: ["Blueberries", "Strawberries", "Acai Pulp", "Almond Milk", "Honey"],
  },
  {
    id: "7",
    slug: "zucchini-noodle-pesto",
    name: "Zucchini Noodle Pesto",
    description: "Fresh spiralized zucchini tossed in homemade basil pesto.",
    price: 13.5,
    rating: 4.5,
    reviews: 55,
    image: "/zucchini-noodles.jpg",
    images: [],
    calories: 280,
    protein: 6,
    carbs: 12,
    fats: 24,
    badges: ["Low-Carb"],
    tags: ["Vegan", "Keto", "Light"],
    vendorId: "v3",
    vendorName: "Sunny Fields",
    category: "vegan",
    labReportId: "LAB-6678",
    ingredients: [],
    restaurantName: "Italian Roots",
    isVeg: true,
    detailedDescription:
      "Light and fresh zucchini noodles tossed in a rich, nutty basil pesto sauce made with pine nuts and extra virgin olive oil.",
    ingredientsList: ["Zucchini", "Basil", "Pine Nuts", "Olive Oil", "Garlic"],
  },
  {
    id: "8",
    slug: "turkey-meatballs",
    name: "Lean Turkey Meatballs",
    description: "Oven-baked turkey meatballs with marinara and roasted broccoli.",
    price: 14.5,
    rating: 4.7,
    reviews: 112,
    image: "/turkey-meatballs.jpg",
    images: [],
    calories: 410,
    protein: 38,
    carbs: 15,
    fats: 14,
    badges: ["High-Protein"],
    tags: ["Dinner", "Family-Favorite"],
    vendorId: "v2",
    vendorName: "Happy Hen Ranch",
    category: "high-protein",
    labReportId: "LAB-9988",
    ingredients: [],
    restaurantName: "Mama's Kitchen",
    isVeg: false,
    discount: 5,
    detailedDescription:
      "Hand-rolled turkey meatballs seasoned with Italian herbs, baked to golden perfection and served with homemade marinara.",
    ingredientsList: ["Ground Turkey", "Breadcrumbs", "Egg", "Marinara Sauce", "Broccoli"],
  },
  {
    id: "9",
    slug: "tofu-stir-fry",
    name: "Spicy Tofu Stir Fry",
    description: "Crispy tofu with bell peppers, snap peas, and ginger-soy glaze.",
    price: 13.99,
    rating: 4.6,
    reviews: 78,
    image: "/tofu-stir-fry.png",
    images: [],
    calories: 390,
    protein: 22,
    carbs: 35,
    fats: 16,
    badges: ["Plant-Based"],
    tags: ["Vegan", "Spicy"],
    vendorId: "v6",
    vendorName: "Asian Roots Co",
    category: "vegan",
    labReportId: "LAB-2234",
    ingredients: [],
    restaurantName: "Wok & Roll",
    isVeg: true,
    detailedDescription:
      "Pan-seared tofu cubes tossed with crunchy bell peppers and snap peas in a savory and spicy ginger-soy glaze.",
    ingredientsList: ["Tofu", "Bell Peppers", "Snap Peas", "Ginger", "Soy Sauce"],
  },
  {
    id: "10",
    slug: "steel-cut-oats",
    name: "Apple Cinnamon Oats",
    description: "Slow-cooked steel cut oats topped with fresh apples and ceylon cinnamon.",
    price: 7.99,
    rating: 4.8,
    reviews: 150,
    image: "/bowl-of-oatmeal.png",
    images: [],
    calories: 310,
    protein: 8,
    carbs: 52,
    fats: 6,
    badges: ["Heart-Healthy"],
    tags: ["Breakfast", "Vegetarian"],
    vendorId: "v7",
    vendorName: "Grains & Co",
    category: "breakfast",
    labReportId: "LAB-4455",
    ingredients: [],
    restaurantName: "Morning Glory",
    isVeg: true,
    detailedDescription:
      "Hearty steel-cut oats slow-cooked to creamy perfection, topped with crisp apple slices and a dusting of warm cinnamon.",
    ingredientsList: ["Steel Cut Oats", "Apples", "Cinnamon", "Almonds", "Maple Syrup"],
  },
  {
    id: "11",
    slug: "bison-chili",
    name: "Lean Bison Chili",
    description: "Rich and smoky chili made with grass-fed bison and kidney beans.",
    price: 16.99,
    rating: 4.9,
    reviews: 205,
    image: "/chili-bowl.jpg",
    images: [],
    calories: 480,
    protein: 45,
    carbs: 28,
    fats: 18,
    badges: ["High-Protein", "Iron-Rich"],
    tags: ["Dinner", "Paleo"],
    vendorId: "v5",
    vendorName: "Rancheros",
    category: "high-protein",
    labReportId: "LAB-7766",
    ingredients: [],
    restaurantName: "The Chili Pot",
    isVeg: false,
    detailedDescription:
      "A robust chili made with lean grass-fed bison, simmered with kidney beans, tomatoes, and a secret blend of spices.",
    ingredientsList: ["Grass-Fed Bison", "Kidney Beans", "Tomatoes", "Chili Powder", "Onions"],
  },
  {
    id: "12",
    slug: "green-detox-juice",
    name: "Green Detox Juice",
    description: "Cold-pressed kale, cucumber, apple, lemon, and ginger.",
    price: 9.5,
    rating: 4.7,
    reviews: 310,
    image: "/vibrant-green-juice.png",
    images: [],
    calories: 120,
    protein: 2,
    carbs: 26,
    fats: 0,
    badges: ["Raw", "Cold-Pressed"],
    tags: ["Beverage", "Detox"],
    vendorId: "v1",
    vendorName: "GreenLeaf Family Farms",
    category: "beverages",
    labReportId: "LAB-9900",
    ingredients: [],
    restaurantName: "Juice Press",
    isVeg: true,
    detailedDescription:
      "A revitalizing cold-pressed juice blend packed with nutrients from fresh kale, cucumber, tart apple, and zesty lemon.",
    ingredientsList: ["Kale", "Cucumber", "Apple", "Lemon", "Ginger"],
  },
]

export const CATEGORIES = [
  { id: "all", name: "All Meals", slug: "all" },
  { id: "vegan", name: "Vegan", slug: "vegan" },
  { id: "high-protein", name: "High Protein", slug: "high-protein" },
  { id: "keto", name: "Keto", slug: "keto" },
  { id: "diabetic-friendly", name: "Diabetic Friendly", slug: "diabetic-friendly" },
  { id: "breakfast", name: "Breakfast", slug: "breakfast" },
  { id: "beverages", name: "Beverages", slug: "beverages" },
]
